title: Pins voor meerdere knoppen instellen
hero_image: images/banner.png
description: Hoe kan je de pinnen voor meerdere knoppen op een Raspberry Pi Pico instellen
version: 4
listed: false
copyedit: false
last_tested: "2022-02-14"
steps:
  - 
    title: Pins voor meerdere knoppen instellen
