---
title: Définir les broches pour plusieurs boutons
hero_image: images/banner.png
description: Comment définir les broches pour plusieurs boutons sur un Raspberry Pi Pico
version: 4
listed: false
copyedit: false
last_tested: "2022-02-14"
steps:
  - title: Définir les broches pour plusieurs boutons
